data:
  bbox_training_annotations: ./data/train_bbox_annotations.json
  segment_training_annotations: data/train_annotations.json
  bbox_train: ./data/train_bbox_images
  segmentation_train: ./data/train_segmentation_images
  labeltype: coco

prelim:
  train_validation_split: 0.9

augmentation:
  enable: true
  gamma:
    range: [0.0, 2.0]     # 1.0 = no change; values <1 darken, >1 brighten
    default: 1.0
  contrast:
    range: [0.0, 2.0]     # 1.0 = no change; values <1 decrease contrast, >1 increase contrast
    default: 1.0
  zoom:
    range: [0, 10]     # 5.0 = current zoom, zoom in < 5 > zoom out
    default: 5.0
  flip:
    flip:
    horizontal: [0.0, 1.0]  # range for horizontal flip
    vertical: [0.0, 1.0]    # range for vertical flip
    default: 0              # default = no flip if random not applied
