data:
  bbox_training_annotations: ./data/train_bbox_annotations.json
  segment_training_annotations: data/train_annotations.json
  bbox_train: ./data/train_bbox_images
  segmentation_train: ./data/train_segmentation_images
  labeltype: coco

prelim:
  train_validation_split: 0.9

augmentation:
  enable: true
  gamma:
    range: [0.8, 1.2]     # 1.0 = no change; values <1 darken, >1 brighten
    default: 1.0
  contrast:
    range: [0.8, 1.3]     # 1.0 = no change; values <1 decrease contrast, >1 increase contrast
    default: 1.0
  zoom:
    range: [0, 10]     # 5.0 = current zoom, zoom in < 5 > zoom out
    default: 5.0
